version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 840943737592.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t repodjango .
      - docker tag repodjango:latest 840943737592.dkr.ecr.sa-east-1.amazonaws.com/repodjango:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 840943737592.dkr.ecr.sa-east-1.amazonaws.com/repodjango:latest
      - printf '[{"name":"MyfistContainerinAws","imageUri":"%s"}]' 840943737592.dkr.ecr.sa-east-1.amazonaws.com/840943737592.dkr.ecr.sa-east-1.amazonaws.com/repodjango:latest:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json