# Generated by Django 4.1.7 on 2023-03-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="images/avatar.png", null=True, upload_to="images/"
            ),
        ),
    ]
